name: CI

on:
  push:
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          sudo apt update
          sudo apt install libssl-dev libnghttp2-dev
          ./configure --with-openssl --with-nghttp2 --with-kcp --with-mqtt
          make libhv evpp

      - name: test
        run: |
          make check
          make run-unittest

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          mkdir cmake-build-win64
          cd cmake-build-win64
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build .

  build-apple:
    name: build-apple
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: build-mac
        run: |
          ./configure
          make libhv evpp examples unittest

      - name: build-ios
        run: |
          mkdir cmake-build-ios
          cd cmake-build-ios
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPLATFORM=OS -DDEPLOYMENT_TARGET=9.0 -DARCHS="arm64"
          cmake --build . --target hv_static --config Release

